### ISSUE TITLE
add-key needs to strip newlines

### ISSUE THREAD

**Issue by tkellen** [MattSurabian/pact#2]
...or listing them does if it doesn't matter.

Based on your presentation if you add a key as an argument, there is no newline, but if you pipe a file, there is.

**Comment by MattSurabian** [comment]
Hmm, so I've been meaning to truncate the bytes read in to allow for comments at the end of the key just as with RSA keys which would also address this. I don't think Pact key-gen adds newlines to the end of the file, but I'll repro and work this out.

**Comment by MattSurabian** [comment]
@tkellen Looks like #3 will take care of this! Thanks.

**Comment by tkellen** [comment]
Nice!
